package cs5004.marblesolitaire.controller;

import org.junit.Before;
import org.junit.Test;

import java.io.InputStreamReader;
import java.io.StringReader;

import cs5004.marblesolitaire.model.impl.MarbleSolitaireModelImpl;

import static org.junit.Assert.assertEquals;

/**
 * This is the test class for the MarbleSolitaireControllerImpl class.
 */
public class MarbleSolitaireControllerImplTest {

  private Appendable appendable;
  private MarbleSolitaireController controller;

  @Before
  public void setUp() {
    appendable = new StringBuilder();
  }

  @Test(expected = IllegalArgumentException.class)
  public void testNullModel() {
    controller = new MarbleSolitaireControllerImpl(new InputStreamReader(System.in), System.out);
    controller.playGame(null);
  }

  @Test(expected = IllegalArgumentException.class)
  public void testNullAp() {
    controller = new MarbleSolitaireControllerImpl(null, System.out);
  }

  @Test(expected = IllegalArgumentException.class)
  public void testNullRd() {
    controller = new MarbleSolitaireControllerImpl(new InputStreamReader(System.in), null);
  }

  @Test(expected = IllegalStateException.class)
  public void testEmptyAp() {
    controller = new MarbleSolitaireControllerImpl(new StringReader(""), System.out);
    controller.playGame(new MarbleSolitaireModelImpl());
  }

  @Test(expected = IllegalStateException.class)
  public void testIncompleteArraySize() {
    controller = new MarbleSolitaireControllerImpl(new StringReader("2 4 2"), System.out);
    controller.playGame(new MarbleSolitaireModelImpl());
  }

  @Test(expected = IllegalStateException.class)
  public void testOutofBoundsMoveNoInputs() {
    controller = new MarbleSolitaireControllerImpl(new StringReader("6 8 9 10"), System.out);
    controller.playGame(new MarbleSolitaireModelImpl());
  }

  @Test(expected = IllegalStateException.class)
  public void testIOExceptionResponse() {
    controller = new MarbleSolitaireControllerImpl(new StringReader("6 8 9 10"),
            new MyAppendable());
    controller.playGame(new MarbleSolitaireModelImpl());
  }

  @Test
  public void testMockModel() {
    controller = new MarbleSolitaireControllerImpl(new StringReader("2 q"),
            appendable);
    controller.playGame(new MyModel());
    assertEquals("Here is the game state for testing purposes\n"
            + "Score: 15\n"
            + "Game quit!\n"
            + "State of game when quit:\n"
            + "Here is the game state for testing purposes\n" + "Score: 15\n"
            + "\n", appendable.toString());
  }

  @Test
  public void testStringMessagesAllErrors() {
    controller = new MarbleSolitaireControllerImpl(new StringReader("w e -6 r -1 4 2 4 4 q"),
            appendable);
    controller.playGame(new MarbleSolitaireModelImpl());
    assertEquals("    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O O O _ O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 32\n"
            + "Error: value must be an integer. Try again.\n"
            + "Error: value must be an integer. Try again.\n"
            + "Error: value must be positive. Try again.\n"
            + "Error: value must be an integer. Try again.\n"
            + "Error: value must be an integer. Try again.\n"
            + "Error: value must be positive. Try again.\n"
            + "    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O _ _ O O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 31\n"
            + "Game quit!\n"
            + "State of game when quit:\n"
            + "    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O _ _ O O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 31\n"
            + "\n", appendable.toString());
  }

  @Test
  public void testGameQuitOneMove() {
    controller = new MarbleSolitaireControllerImpl(new StringReader("4 2 4 4 q"),
            appendable);
    controller.playGame(new MarbleSolitaireModelImpl());
    assertEquals("    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O O O _ O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 32\n"
            + "    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O _ _ O O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 31\n"
            + "Game quit!\n"
            + "State of game when quit:\n"
            + "    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O _ _ O O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 31\n"
            + "\n", appendable.toString());
  }

  @Test
  public void testGameQuitMiddleOneMove() {
    controller = new MarbleSolitaireControllerImpl(new StringReader("4 2 q 4 4"),
            appendable);
    controller.playGame(new MarbleSolitaireModelImpl());
    assertEquals("    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O O O _ O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 32\n"
            + "Game quit!\n"
            + "State of game when quit:\n"
            + "    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O O O _ O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 32\n"
            + "\n", appendable.toString());
  }

  @Test
  public void playGameQuitMiddle() {
    controller = new MarbleSolitaireControllerImpl(new StringReader("4 2 4 4 6 3 4 3 5 3 q"),
            appendable);
    controller.playGame(new MarbleSolitaireModelImpl());
    assertEquals("    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O O O _ O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 32\n"
            + "    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O _ _ O O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 31\n"
            + "    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O _ O O O O O\n"
            + "O O _ O O O O\n"
            + "    _ O O\n"
            + "    O O O\n"
            + "Score: 30\n"
            + "Game quit!\n"
            + "State of game when quit:\n"
            + "    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O _ O O O O O\n"
            + "O O _ O O O O\n"
            + "    _ O O\n"
            + "    O O O\n"
            + "Score: 30\n"
            + "\n", appendable.toString());
  }

  @Test
  public void testGameWordsInsideInput() {
    controller = new MarbleSolitaireControllerImpl(new StringReader("4 2 happy 4 days 4 q"),
            appendable);
    controller.playGame(new MarbleSolitaireModelImpl());
    assertEquals("    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O O O _ O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 32\n"
            + "Error: value must be an integer. Try again.\n"
            + "Error: value must be an integer. Try again.\n"
            + "    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O _ _ O O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 31\n"
            + "Game quit!\n"
            + "State of game when quit:\n"
            + "    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O _ _ O O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 31\n"
            + "\n", appendable.toString());
  }

  @Test
  public void testNegativeNumbers() {
    controller = new MarbleSolitaireControllerImpl(new StringReader("4 2 -4 -5 -1 4 4 q"),
            appendable);
    controller.playGame(new MarbleSolitaireModelImpl());
    assertEquals("    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O O O _ O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 32\n"
            + "Error: value must be positive. Try again.\n"
            + "Error: value must be positive. Try again.\n"
            + "Error: value must be positive. Try again.\n"
            + "    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O _ _ O O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 31\n"
            + "Game quit!\n"
            + "State of game when quit:\n"
            + "    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O _ _ O O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 31\n"
            + "\n", appendable.toString());
  }

  @Test
  public void playGameOver() {
    controller = new MarbleSolitaireControllerImpl(new StringReader("2 4 4 4 "
            + "3 6 3 4 "
            + "1 5 3 5 "
            + "4 5 2 5 "
            + "6 5 4 5 "
            + "5 7 5 5 "
            + "5 4 5 6 "
            + "3 7 5 7 "
            + "5 7 5 5 "
            + "3 3 3 5 "
            + "3 1 3 3 "
            + "5 2 5 4 "
            + "5 4 5 6 "
            + "5 6 3 6 "
            + "3 6 3 4 "
            + "3 4 3 2 "
            + "7 3 5 3 "
            + "4 3 6 3 "
            + "7 5 7 3 "
            + "7 3 5 3 "
            + "5 1 3 1 "
            + "3 1 3 3 "
            + "1 3 1 5 "
            + "1 5 3 5 "
            + "3 5 5 5 "
            + "2 3 4 3 "
            + "4 3 6 3 "
            + "6 3 6 5 "
            + "6 5 4 5 "
            + "4 4 4 6"),
            appendable);
    controller.playGame(new MarbleSolitaireModelImpl());
    assertEquals("    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O O O _ O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 32\n"
            + "    O O O\n"
            + "    O _ O\n"
            + "O O O _ O O O\n"
            + "O O O O O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 31\n"
            + "    O O O\n"
            + "    O _ O\n"
            + "O O O O _ _ O\n"
            + "O O O O O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 30\n"
            + "    O O _\n"
            + "    O _ _\n"
            + "O O O O O _ O\n"
            + "O O O O O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 29\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "O O O O _ _ O\n"
            + "O O O O _ O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 28\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "O O O O _ _ O\n"
            + "O O O O O O O\n"
            + "O O O O _ O O\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 27\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "O O O O _ _ O\n"
            + "O O O O O O O\n"
            + "O O O O O _ _\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 26\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "O O O O _ _ O\n"
            + "O O O O O O O\n"
            + "O O O _ _ O _\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 25\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "O O O O _ _ _\n"
            + "O O O O O O _\n"
            + "O O O _ _ O O\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 24\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "O O O O _ _ _\n"
            + "O O O O O O _\n"
            + "O O O _ O _ _\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 23\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "O O _ _ O _ _\n"
            + "O O O O O O _\n"
            + "O O O _ O _ _\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 22\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "_ _ O _ O _ _\n"
            + "O O O O O O _\n"
            + "O O O _ O _ _\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 21\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "_ _ O _ O _ _\n"
            + "O O O O O O _\n"
            + "O _ _ O O _ _\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 20\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "_ _ O _ O _ _\n"
            + "O O O O O O _\n"
            + "O _ _ _ _ O _\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 19\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "_ _ O _ O O _\n"
            + "O O O O O _ _\n"
            + "O _ _ _ _ _ _\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 18\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "_ _ O O _ _ _\n"
            + "O O O O O _ _\n"
            + "O _ _ _ _ _ _\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 17\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "_ O _ _ _ _ _\n"
            + "O O O O O _ _\n"
            + "O _ _ _ _ _ _\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 16\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "_ O _ _ _ _ _\n"
            + "O O O O O _ _\n"
            + "O _ O _ _ _ _\n"
            + "    _ O _\n"
            + "    _ O O\n"
            + "Score: 15\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "_ O _ _ _ _ _\n"
            + "O O _ O O _ _\n"
            + "O _ _ _ _ _ _\n"
            + "    O O _\n"
            + "    _ O O\n"
            + "Score: 14\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "_ O _ _ _ _ _\n"
            + "O O _ O O _ _\n"
            + "O _ _ _ _ _ _\n"
            + "    O O _\n"
            + "    O _ _\n"
            + "Score: 13\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "_ O _ _ _ _ _\n"
            + "O O _ O O _ _\n"
            + "O _ O _ _ _ _\n"
            + "    _ O _\n"
            + "    _ _ _\n"
            + "Score: 12\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "O O _ _ _ _ _\n"
            + "_ O _ O O _ _\n"
            + "_ _ O _ _ _ _\n"
            + "    _ O _\n"
            + "    _ _ _\n"
            + "Score: 11\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "_ _ O _ _ _ _\n"
            + "_ O _ O O _ _\n"
            + "_ _ O _ _ _ _\n"
            + "    _ O _\n"
            + "    _ _ _\n"
            + "Score: 10\n"
            + "    _ _ O\n"
            + "    O _ O\n"
            + "_ _ O _ _ _ _\n"
            + "_ O _ O O _ _\n"
            + "_ _ O _ _ _ _\n"
            + "    _ O _\n"
            + "    _ _ _\n"
            + "Score: 9\n"
            + "    _ _ _\n"
            + "    O _ _\n"
            + "_ _ O _ O _ _\n"
            + "_ O _ O O _ _\n"
            + "_ _ O _ _ _ _\n"
            + "    _ O _\n"
            + "    _ _ _\n"
            + "Score: 8\n"
            + "    _ _ _\n"
            + "    O _ _\n"
            + "_ _ O _ _ _ _\n"
            + "_ O _ O _ _ _\n"
            + "_ _ O _ O _ _\n"
            + "    _ O _\n"
            + "    _ _ _\n"
            + "Score: 7\n"
            + "    _ _ _\n"
            + "    _ _ _\n"
            + "_ _ _ _ _ _ _\n"
            + "_ O O O _ _ _\n"
            + "_ _ O _ O _ _\n"
            + "    _ O _\n"
            + "    _ _ _\n"
            + "Score: 6\n"
            + "    _ _ _\n"
            + "    _ _ _\n"
            + "_ _ _ _ _ _ _\n"
            + "_ O _ O _ _ _\n"
            + "_ _ _ _ O _ _\n"
            + "    O O _\n"
            + "    _ _ _\n"
            + "Score: 5\n"
            + "    _ _ _\n"
            + "    _ _ _\n"
            + "_ _ _ _ _ _ _\n"
            + "_ O _ O _ _ _\n"
            + "_ _ _ _ O _ _\n"
            + "    _ _ O\n"
            + "    _ _ _\n"
            + "Score: 4\n"
            + "    _ _ _\n"
            + "    _ _ _\n"
            + "_ _ _ _ _ _ _\n"
            + "_ O _ O O _ _\n"
            + "_ _ _ _ _ _ _\n"
            + "    _ _ _\n"
            + "    _ _ _\n"
            + "Score: 3\n"
            + "    _ _ _\n"
            + "    _ _ _\n"
            + "_ _ _ _ _ _ _\n"
            + "_ O _ _ _ O _\n"
            + "_ _ _ _ _ _ _\n"
            + "    _ _ _\n"
            + "    _ _ _\n"
            + "Score: 2\n"
            + "Game over!\n"
            + "    _ _ _\n"
            + "    _ _ _\n"
            + "_ _ _ _ _ _ _\n"
            + "_ O _ _ _ O _\n"
            + "_ _ _ _ _ _ _\n"
            + "    _ _ _\n"
            + "    _ _ _\n"
            + "Score: 2\n", appendable.toString());
  }

  @Test
  public void playGameWon() {
    controller = new MarbleSolitaireControllerImpl(new StringReader("2 4 4 4 "
            + "3 6 3 4 "
            + "1 5 3 5 "
            + "4 5 2 5 "
            + "6 5 4 5 "
            + "5 7 5 5 "
            + "5 4 5 6 "
            + "3 7 5 7 "
            + "5 7 5 5 "
            + "3 3 3 5 "
            + "3 1 3 3 "
            + "5 2 5 4 "
            + "5 4 5 6 "
            + "5 6 3 6 "
            + "3 6 3 4 "
            + "3 4 3 2 "
            + "7 3 5 3 "
            + "4 3 6 3 "
            + "7 5 7 3 "
            + "7 3 5 3 "
            + "5 1 3 1 "
            + "3 1 3 3 "
            + "1 3 1 5 "
            + "1 5 3 5 "
            + "3 5 5 5 "
            + "2 3 4 3 "
            + "4 3 6 3 "
            + "6 3 6 5 "
            + "6 5 4 5 "
            + "4 5 4 3 "
            + "4 2 4 4 q"),
            appendable);
    controller.playGame(new MarbleSolitaireModelImpl());
    assertEquals("    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O O O _ O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 32\n"
            + "    O O O\n"
            + "    O _ O\n"
            + "O O O _ O O O\n"
            + "O O O O O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 31\n"
            + "    O O O\n"
            + "    O _ O\n"
            + "O O O O _ _ O\n"
            + "O O O O O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 30\n"
            + "    O O _\n"
            + "    O _ _\n"
            + "O O O O O _ O\n"
            + "O O O O O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 29\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "O O O O _ _ O\n"
            + "O O O O _ O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 28\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "O O O O _ _ O\n"
            + "O O O O O O O\n"
            + "O O O O _ O O\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 27\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "O O O O _ _ O\n"
            + "O O O O O O O\n"
            + "O O O O O _ _\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 26\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "O O O O _ _ O\n"
            + "O O O O O O O\n"
            + "O O O _ _ O _\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 25\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "O O O O _ _ _\n"
            + "O O O O O O _\n"
            + "O O O _ _ O O\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 24\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "O O O O _ _ _\n"
            + "O O O O O O _\n"
            + "O O O _ O _ _\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 23\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "O O _ _ O _ _\n"
            + "O O O O O O _\n"
            + "O O O _ O _ _\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 22\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "_ _ O _ O _ _\n"
            + "O O O O O O _\n"
            + "O O O _ O _ _\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 21\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "_ _ O _ O _ _\n"
            + "O O O O O O _\n"
            + "O _ _ O O _ _\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 20\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "_ _ O _ O _ _\n"
            + "O O O O O O _\n"
            + "O _ _ _ _ O _\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 19\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "_ _ O _ O O _\n"
            + "O O O O O _ _\n"
            + "O _ _ _ _ _ _\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 18\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "_ _ O O _ _ _\n"
            + "O O O O O _ _\n"
            + "O _ _ _ _ _ _\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 17\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "_ O _ _ _ _ _\n"
            + "O O O O O _ _\n"
            + "O _ _ _ _ _ _\n"
            + "    O O _\n"
            + "    O O O\n"
            + "Score: 16\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "_ O _ _ _ _ _\n"
            + "O O O O O _ _\n"
            + "O _ O _ _ _ _\n"
            + "    _ O _\n"
            + "    _ O O\n"
            + "Score: 15\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "_ O _ _ _ _ _\n"
            + "O O _ O O _ _\n"
            + "O _ _ _ _ _ _\n"
            + "    O O _\n"
            + "    _ O O\n"
            + "Score: 14\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "_ O _ _ _ _ _\n"
            + "O O _ O O _ _\n"
            + "O _ _ _ _ _ _\n"
            + "    O O _\n"
            + "    O _ _\n"
            + "Score: 13\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "_ O _ _ _ _ _\n"
            + "O O _ O O _ _\n"
            + "O _ O _ _ _ _\n"
            + "    _ O _\n"
            + "    _ _ _\n"
            + "Score: 12\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "O O _ _ _ _ _\n"
            + "_ O _ O O _ _\n"
            + "_ _ O _ _ _ _\n"
            + "    _ O _\n"
            + "    _ _ _\n"
            + "Score: 11\n"
            + "    O O _\n"
            + "    O _ O\n"
            + "_ _ O _ _ _ _\n"
            + "_ O _ O O _ _\n"
            + "_ _ O _ _ _ _\n"
            + "    _ O _\n"
            + "    _ _ _\n"
            + "Score: 10\n"
            + "    _ _ O\n"
            + "    O _ O\n"
            + "_ _ O _ _ _ _\n"
            + "_ O _ O O _ _\n"
            + "_ _ O _ _ _ _\n"
            + "    _ O _\n"
            + "    _ _ _\n"
            + "Score: 9\n"
            + "    _ _ _\n"
            + "    O _ _\n"
            + "_ _ O _ O _ _\n"
            + "_ O _ O O _ _\n"
            + "_ _ O _ _ _ _\n"
            + "    _ O _\n"
            + "    _ _ _\n"
            + "Score: 8\n"
            + "    _ _ _\n"
            + "    O _ _\n"
            + "_ _ O _ _ _ _\n"
            + "_ O _ O _ _ _\n"
            + "_ _ O _ O _ _\n"
            + "    _ O _\n"
            + "    _ _ _\n"
            + "Score: 7\n"
            + "    _ _ _\n"
            + "    _ _ _\n"
            + "_ _ _ _ _ _ _\n"
            + "_ O O O _ _ _\n"
            + "_ _ O _ O _ _\n"
            + "    _ O _\n"
            + "    _ _ _\n"
            + "Score: 6\n"
            + "    _ _ _\n"
            + "    _ _ _\n"
            + "_ _ _ _ _ _ _\n"
            + "_ O _ O _ _ _\n"
            + "_ _ _ _ O _ _\n"
            + "    O O _\n"
            + "    _ _ _\n"
            + "Score: 5\n"
            + "    _ _ _\n"
            + "    _ _ _\n"
            + "_ _ _ _ _ _ _\n"
            + "_ O _ O _ _ _\n"
            + "_ _ _ _ O _ _\n"
            + "    _ _ O\n"
            + "    _ _ _\n"
            + "Score: 4\n"
            + "    _ _ _\n"
            + "    _ _ _\n"
            + "_ _ _ _ _ _ _\n"
            + "_ O _ O O _ _\n"
            + "_ _ _ _ _ _ _\n"
            + "    _ _ _\n"
            + "    _ _ _\n"
            + "Score: 3\n"
            + "    _ _ _\n"
            + "    _ _ _\n"
            + "_ _ _ _ _ _ _\n"
            + "_ O O _ _ _ _\n"
            + "_ _ _ _ _ _ _\n"
            + "    _ _ _\n"
            + "    _ _ _\n"
            + "Score: 2\n"
            + "    _ _ _\n"
            + "    _ _ _\n"
            + "_ _ _ _ _ _ _\n"
            + "_ _ _ O _ _ _\n"
            + "_ _ _ _ _ _ _\n"
            + "    _ _ _\n"
            + "    _ _ _\n"
            + "Score: 1\n"
            + "Game over!\n"
            + "    _ _ _\n"
            + "    _ _ _\n"
            + "_ _ _ _ _ _ _\n"
            + "_ _ _ O _ _ _\n"
            + "_ _ _ _ _ _ _\n"
            + "    _ _ _\n"
            + "    _ _ _\n"
            + "Score: 1\n", appendable.toString());
  }

  @Test
  public void playGameRandomErrorInJUnit() {
    Appendable appendable2 = new StringBuilder();
    controller = new MarbleSolitaireControllerImpl(new StringReader("4 2 4 4 "
            + "4 5 4 3 "
            + "2 4 4 4 "
            + "2 5 4 5 "
            + "5 4 3 4 "
            + "5 6 5 4 "
            + "4 6 4 4 "
            + "7 5 5 5 "
            + "3 7 3 5 "
            + "6 3 6 5 "
            + "5 5 7 5 "
            + "5 3 5 5 "
            + "5 1 5 3 "
            + "3 1 5 1 "
            + "5 7 3 7 "
            + "4 3 4 5 "
            + "2 3 4 3 "
            + "3 5 3 3 "
            + "3 3 3 1 "
            + "4 5 6 5 "
            + "5 3 3 3 "
            + "7 5 5 5 "
            + "7 3 7 5 q"), appendable2);
    controller.playGame(new MarbleSolitaireModelImpl(3, 3, 3));
    assertEquals("    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O O O _ O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 32\n"
            + "    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O _ _ O O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 31\n"
            + "    O O O\n"
            + "    O O O\n"
            + "O O O O O O O\n"
            + "O _ O _ _ O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 30\n"
            + "    O O O\n"
            + "    O _ O\n"
            + "O O O _ O O O\n"
            + "O _ O O _ O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 29\n"
            + "    O O O\n"
            + "    O _ _\n"
            + "O O O _ _ O O\n"
            + "O _ O O O O O\n"
            + "O O O O O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 28\n"
            + "    O O O\n"
            + "    O _ _\n"
            + "O O O O _ O O\n"
            + "O _ O _ O O O\n"
            + "O O O _ O O O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 27\n"
            + "    O O O\n"
            + "    O _ _\n"
            + "O O O O _ O O\n"
            + "O _ O _ O O O\n"
            + "O O O O _ _ O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 26\n"
            + "    O O O\n"
            + "    O _ _\n"
            + "O O O O _ O O\n"
            + "O _ O O _ _ O\n"
            + "O O O O _ _ O\n"
            + "    O O O\n"
            + "    O O O\n"
            + "Score: 25\n"
            + "    O O O\n"
            + "    O _ _\n"
            + "O O O O _ O O\n"
            + "O _ O O _ _ O\n"
            + "O O O O O _ O\n"
            + "    O O _\n"
            + "    O O _\n"
            + "Score: 24\n"
            + "    O O O\n"
            + "    O _ _\n"
            + "O O O O O _ _\n"
            + "O _ O O _ _ O\n"
            + "O O O O O _ O\n"
            + "    O O _\n"
            + "    O O _\n"
            + "Score: 23\n"
            + "    O O O\n"
            + "    O _ _\n"
            + "O O O O O _ _\n"
            + "O _ O O _ _ O\n"
            + "O O O O O _ O\n"
            + "    _ _ O\n"
            + "    O O _\n"
            + "Score: 22\n"
            + "    O O O\n"
            + "    O _ _\n"
            + "O O O O O _ _\n"
            + "O _ O O _ _ O\n"
            + "O O O O _ _ O\n"
            + "    _ _ _\n"
            + "    O O O\n"
            + "Score: 21\n"
            + "    O O O\n"
            + "    O _ _\n"
            + "O O O O O _ _\n"
            + "O _ O O _ _ O\n"
            + "O O _ _ O _ O\n"
            + "    _ _ _\n"
            + "    O O O\n"
            + "Score: 20\n"
            + "    O O O\n"
            + "    O _ _\n"
            + "O O O O O _ _\n"
            + "O _ O O _ _ O\n"
            + "_ _ O _ O _ O\n"
            + "    _ _ _\n"
            + "    O O O\n"
            + "Score: 19\n"
            + "    O O O\n"
            + "    O _ _\n"
            + "_ O O O O _ _\n"
            + "_ _ O O _ _ O\n"
            + "O _ O _ O _ O\n"
            + "    _ _ _\n"
            + "    O O O\n"
            + "Score: 18\n"
            + "    O O O\n"
            + "    O _ _\n"
            + "_ O O O O _ O\n"
            + "_ _ O O _ _ _\n"
            + "O _ O _ O _ _\n"
            + "    _ _ _\n"
            + "    O O O\n"
            + "Score: 17\n"
            + "    O O O\n"
            + "    O _ _\n"
            + "_ O O O O _ O\n"
            + "_ _ _ _ O _ _\n"
            + "O _ O _ O _ _\n"
            + "    _ _ _\n"
            + "    O O O\n"
            + "Score: 16\n"
            + "    O O O\n"
            + "    _ _ _\n"
            + "_ O _ O O _ O\n"
            + "_ _ O _ O _ _\n"
            + "O _ O _ O _ _\n"
            + "    _ _ _\n"
            + "    O O O\n"
            + "Score: 15\n"
            + "    O O O\n"
            + "    _ _ _\n"
            + "_ O O _ _ _ O\n"
            + "_ _ O _ O _ _\n"
            + "O _ O _ O _ _\n"
            + "    _ _ _\n"
            + "    O O O\n"
            + "Score: 14\n"
            + "    O O O\n"
            + "    _ _ _\n"
            + "O _ _ _ _ _ O\n"
            + "_ _ O _ O _ _\n"
            + "O _ O _ O _ _\n"
            + "    _ _ _\n"
            + "    O O O\n"
            + "Score: 13\n"
            + "    O O O\n"
            + "    _ _ _\n"
            + "O _ _ _ _ _ O\n"
            + "_ _ O _ _ _ _\n"
            + "O _ O _ _ _ _\n"
            + "    _ _ O\n"
            + "    O O O\n"
            + "Score: 12\n"
            + "    O O O\n"
            + "    _ _ _\n"
            + "O _ O _ _ _ O\n"
            + "_ _ _ _ _ _ _\n"
            + "O _ _ _ _ _ _\n"
            + "    _ _ O\n"
            + "    O O O\n"
            + "Score: 11\n"
            + "    O O O\n"
            + "    _ _ _\n"
            + "O _ O _ _ _ O\n"
            + "_ _ _ _ _ _ _\n"
            + "O _ _ _ O _ _\n"
            + "    _ _ _\n"
            + "    O O _\n"
            + "Score: 10\n"
            + "    O O O\n"
            + "    _ _ _\n"
            + "O _ O _ _ _ O\n"
            + "_ _ _ _ _ _ _\n"
            + "O _ _ _ O _ _\n"
            + "    _ _ _\n"
            + "    _ _ O\n"
            + "Score: 9\n"
            + "Game over!\n"
            + "    O O O\n"
            + "    _ _ _\n"
            + "O _ O _ _ _ O\n"
            + "_ _ _ _ _ _ _\n"
            + "O _ _ _ O _ _\n"
            + "    _ _ _\n"
            + "    _ _ O\n"
            + "Score: 9\n", appendable2.toString());
  }
}